import { cn } from '@/lib/utils';

import Footer from '@/components/home/footer/footer';
import ResponsiveNav from '@/components/home/navbar/responsive-nav';
import { Toaster } from '@/components/ui/toaster';
import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { Poppins, Roboto } from 'next/font/google';
import localFont from 'next/font/local';
import { cookies } from 'next/headers';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
});
const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    template: '%s | Finance App',
    default: 'Finance App',
  },
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = (cookieStore.get('theme')?.value ?? 'light') as
    | 'dark'
    | 'light';

  return (
    <html lang='en' className={cn(theme)}>
      <body
        className={cn(
          'flex min-h-screen flex-col antialiased',
          roboto.className,
          poppins.className,
          geistSans.variable,
          geistMono.variable
        )}
      >
        <SessionProvider>
          {/* <PageHeader className='w-full' /> */}
          <ResponsiveNav />
          <div className='flex h-full flex-col justify-between'>
            <div>{children}</div>
            {/* <footer className='mt-auto py-4 text-center'>&copy;Footer</footer> */}
            <Footer />
          </div>
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
